// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('js/dist/alert.js');
require('js/dist/button.js');
require('js/dist/carousel.js');
require('js/dist/collapse.js');
require('js/dist/dropdown.js');
require('js/dist/modal.js');
require('js/dist/popover.js');
require('js/scrollspy.js');
require('js/dist/tab.js');
require('js/dist/tooltip.js');